#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not
 * want to edit it directly.
 */

enum tap_dance_codes {
    DANCE_PUNTO,
    DANCE_VIRGOLA,
    DANCE_A,
    DANCE_E,
    DANCE_I,
    DANCE_U,
    DANCE_MIN,
    DANCE_PLUS,
    DANCE_Z,
    DANCE_X,
    DANCE_C,
    DANCE_V,
    DANCE_TAB,
};

enum my_keycodes {
    TAB_MELEE = SAFE_RANGE,
    Z_OR_ONE,
    X_OR_TWO,
    C_OR_THREE,
    V_OR_FIVE,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            LALT_T(KC_Q),   KC_W,     KC_F,     KC_P,    KC_B,                          KC_J,   KC_L, TD(DANCE_U),   KC_Y,  KC_SCLN,
            //------------------------------------------------------------------------------       ----------------------------------------------------------------------------
            TD(DANCE_A),    KC_R,    MT(MOD_RALT,KC_S),    MT(MOD_LGUI,KC_T),    KC_G,     KC_M,   KC_N,   TD(DANCE_E),  TD(DANCE_I),  KC_O,
            //------------------------------------------------------------------------------       ----------------------------------------------------------------------------
            KC_Z,   KC_X,  KC_C,   KC_D,  KC_V,                                 KC_K,  KC_H,   TD(DANCE_VIRGOLA),   TD(DANCE_PUNTO),KC_SLSH,
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            OSM(MOD_LSFT), LCTL_T(KC_SPACE),             KC_BSPC, TO(1)
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            ),
    [1] = LAYOUT_split_3x5_2(
            KC_ESCAPE,LSFT(KC_6),  RALT(KC_E) , LSFT(KC_4), LSFT(KC_5),    LSFT(KC_8), LSFT(KC_9), KC_GRV ,LSFT(KC_GRV), KC_DEL ,
            //----------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            KC_TAB, RALT(KC_QUOT), LSFT(KC_EQL), RALT(KC_EQL),  RALT(KC_MINS),  KC_SLSH, TD(DANCE_PLUS), LSFT(KC_7), LSFT(KC_0), KC_ENTER,

            //----------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            RALT(KC_SCLN), KC_MINS,  LSFT(KC_2),KC_NUBS, LSFT(KC_NUBS),     RSA(KC_LBRC), RALT(KC_LBRC), RALT(KC_RBRC), RSA(KC_RBRC),TO(3)   ,
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            TO(0) ,OSM(MOD_LALT),OSM(MOD_LCTL)      ,TO(2) 
            ),
    [2] = LAYOUT_split_3x5_2(
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            KC_ESCAPE,      KC_MEDIA_PLAY_PAUSE,KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,LSFT(KC_MINS),KC_SLSH,   KC_7,  KC_8, KC_9,KC_BSPC,
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            KC_TAB,  KC_TRANSPARENT, KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,LSFT(KC_EQL),   LSFT(KC_0),   KC_4, KC_5, KC_6,   KC_ENTER,
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            QK_BOOT,   KC_KP_ASTERISK, KC_BRIGHTNESS_DOWN,KC_BRIGHTNESS_UP,KC_KP_DOT,   KC_0,   KC_1, KC_2, KC_3,   TO(3),
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            TO(0), KC_LGUI,OSM(MOD_LCTL) ,TO(1)
            ),
    [3] =
        LAYOUT_split_3x5_2(
                KC_ESCAPE,   KC_MS_WH_LEFT,  KC_MS_UP,       KC_MS_WH_RIGHT, RCTL(KC_F), LALT(KC_LEFT),LCTL(LSFT(KC_TAB)),LCTL(KC_TAB),   LALT(KC_RIGHT),KC_TRANSPARENT, 
                //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
                KC_TAB,   KC_MS_LEFT,     KC_MS_DOWN,     KC_MS_RIGHT,    MT(MOD_LGUI,KC_DEL),    KC_LEFT,   MT(MOD_RGUI,KC_DOWN), MT(MOD_RALT,KC_UP),   KC_RIGHT,   KC_ENTER,     
                //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
                KC_MS_BTN1,   KC_MS_BTN2,     KC_MS_WH_UP,    KC_MS_WH_DOWN, KC_TRANSPARENT, LCTL(KC_T),     KC_MS_ACCEL0,   KC_MS_ACCEL1,   KC_MS_ACCEL2,   LCTL(KC_W), 
                //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
                TO(0),KC_LCTL,TO(4),                                   TO(1)),

    [4] = LAYOUT_split_3x5_2(
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            KC_SPACE,   KC_Q,     KC_W,     KC_E,    KC_R,                          KC_AUDIO_VOL_UP,   KC_AUDIO_VOL_DOWN, KC_BRIGHTNESS_UP,   KC_BRIGHTNESS_DOWN,  KC_ESCAPE,
            //------------------------------------------------------------------------------       ----------------------------------------------------------------------------
            TD(DANCE_TAB),    KC_A,    KC_S,    KC_D,    KC_G,                   KC_LEFT,  KC_UP,  KC_DOWN, KC_RIGHT, KC_MS_WH_UP,
            //------------------------------------------------------------------------------       ----------------------------------------------------------------------------
            OSM(MOD_LCTL),   TD(DANCE_Z),  TD(DANCE_X),   TD(DANCE_C),  TD(DANCE_V),            KC_MS_LEFT, KC_MS_UP, KC_MS_DOWN, KC_MS_RIGHT, KC_MS_WH_DOWN,
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            KC_LALT, OSM(MOD_LSFT),             KC_BSPC, TO(1)
            //---------------------------------------------------------------------------------------       ----------------------------------------------------------------------------------
            ),
};

// #if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE) const
// uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
// 
// }; #endif // defined(ENCODER_ENABLE) &&
// defined(ENCODER_MAP_ENABLE)

extern bool g_suspend_state;
#define GET_TAP_KC(dual_role_key) dual_role_key & 0xFF
uint16_t last_keycode = KC_NO;
uint8_t last_modifier = 0;

typedef struct {
    bool is_press_action;
    uint8_t step;
} tap;

enum {
    SINGLE_TAP = 1,
    SINGLE_HOLD,
    DOUBLE_TAP,
    DOUBLE_HOLD,
    DOUBLE_SINGLE_TAP,
    MORE_TAPS
};

static tap dance_state = {
    .is_press_action = true,
    .step = 0
};

void on_dance_virgola(tap_dance_state_t *state, void *user_data);
uint8_t dance_virgola_dance_step(tap_dance_state_t *state);
void dance_virgola_finished(tap_dance_state_t *state, void *user_data);
void dance_virgola_reset(tap_dance_state_t *state, void *user_data);

void on_dance_virgola(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_COMM);
        tap_code16(KC_COMM);
        tap_code16(KC_COMM);
    }
    if(state->count > 3) {
        tap_code16(KC_COMM);
    }
}

uint8_t dance_virgola_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_virgola_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_virgola_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_COMM); break;
        case SINGLE_HOLD: register_code16(S(KC_MINS)); break;
        case DOUBLE_TAP: register_code16(KC_COMM); register_code16(KC_COMM); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_COMM); register_code16(KC_COMM);
    }
}

void dance_virgola_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_COMM); break;
        case SINGLE_HOLD: unregister_code16(S(KC_MINS)); break;
        case DOUBLE_TAP: unregister_code16(KC_COMM); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(S(KC_MINS)); break;
    }
    dance_state.step = 0;
}

void on_dance_punto(tap_dance_state_t *state, void *user_data);
uint8_t dance_punto_dance_step(tap_dance_state_t *state);
void dance_punto_finished(tap_dance_state_t *state, void *user_data);
void dance_punto_reset(tap_dance_state_t *state, void *user_data);

void on_dance_punto(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_DOT);
        tap_code16(KC_DOT);
        tap_code16(KC_DOT);
    }
    if(state->count > 3) {
        tap_code16(KC_DOT);
    }
}

uint8_t dance_punto_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_punto_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_punto_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_DOT); break;
        case SINGLE_HOLD: register_code16(KC_EXLM); break;
        case DOUBLE_TAP: register_code16(KC_DOT); register_code16(KC_DOT); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_DOT); register_code16(KC_DOT);
    }
}

void dance_punto_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_DOT); break;
        case SINGLE_HOLD: unregister_code16(KC_EXLM); break;
        case DOUBLE_TAP: unregister_code16(KC_DOT); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_DOT); break;
    }
    dance_state.step = 0;
}

void on_dance_a(tap_dance_state_t *state, void *user_data);
uint8_t dance_a_dance_step(tap_dance_state_t *state);
void dance_a_finished(tap_dance_state_t *state, void *user_data);
void dance_a_reset(tap_dance_state_t *state, void *user_data);

void on_dance_a(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_A);
        tap_code16(KC_A);
        tap_code16(KC_A);
    }
    if(state->count > 3) {
        tap_code16(KC_A);
    }
}

uint8_t dance_a_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_a_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_a_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_A); break;
        case SINGLE_HOLD: register_code16(KC_QUOT); break;
        case DOUBLE_TAP: register_code16(KC_A); register_code16(KC_A); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_A); register_code16(KC_A);
    }
}

void dance_a_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_A); break;
        case SINGLE_HOLD: unregister_code16(KC_QUOT); break;
        case DOUBLE_TAP: unregister_code16(KC_A); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_QUOT); break;
    }
    dance_state.step = 0;
}
void on_dance_e(tap_dance_state_t *state, void *user_data);
uint8_t dance_e_dance_step(tap_dance_state_t *state);
void dance_e_finished(tap_dance_state_t *state, void *user_data);
void dance_e_reset(tap_dance_state_t *state, void *user_data);

void on_dance_e(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_E);
        tap_code16(KC_E);
        tap_code16(KC_E);
    }
    if(state->count > 3) {
        tap_code16(KC_E);
    }
}

uint8_t dance_e_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_e_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_e_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_E); break;
        case SINGLE_HOLD: register_code16(KC_LBRC); break;
        case DOUBLE_TAP: register_code16(KC_E); register_code16(KC_E); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_E); register_code16(KC_E);
    }
}

void dance_e_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_E); break;
        case SINGLE_HOLD: unregister_code16(KC_LBRC); break;
        case DOUBLE_TAP: unregister_code16(KC_E); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_LBRC); break;
    }
    dance_state.step = 0;
}
void on_dance_i(tap_dance_state_t *state, void *user_data);
uint8_t dance_i_dance_step(tap_dance_state_t *state);
void dance_i_finished(tap_dance_state_t *state, void *user_data);
void dance_i_reset(tap_dance_state_t *state, void *user_data);

void on_dance_i(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_I);
        tap_code16(KC_I);
        tap_code16(KC_I);
    }
    if(state->count > 3) {
        tap_code16(KC_I);
    }
}

uint8_t dance_i_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_i_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_i_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_I); break;
        case SINGLE_HOLD: register_code16(KC_EQL); break;
        case DOUBLE_TAP: register_code16(KC_I); register_code16(KC_I); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_I); register_code16(KC_I);
    }
}

void dance_i_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_I); break;
        case SINGLE_HOLD: unregister_code16(KC_EQL); break;
        case DOUBLE_TAP: unregister_code16(KC_I); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_EQL); break;
    }
    dance_state.step = 0;
}

void on_dance_u(tap_dance_state_t *state, void *user_data);
uint8_t dance_u_dance_step(tap_dance_state_t *state);
void dance_u_finished(tap_dance_state_t *state, void *user_data);
void dance_u_reset(tap_dance_state_t *state, void *user_data);

void on_dance_u(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_U);
        tap_code16(KC_U);
        tap_code16(KC_U);
    }
    if(state->count > 3) {
        tap_code16(KC_U);
    }
}

uint8_t dance_u_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_u_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_u_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_U); break;
        case SINGLE_HOLD: register_code16(KC_NUHS); break;
        case DOUBLE_TAP: register_code16(KC_U); register_code16(KC_U); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_U); register_code16(KC_U);
    }
}

void dance_u_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_U); break;
        case SINGLE_HOLD: unregister_code16(KC_NUHS); break;
        case DOUBLE_TAP: unregister_code16(KC_U); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_NUHS); break;
    }
    dance_state.step = 0;
}

void on_dance_min(tap_dance_state_t *state, void *user_data);
uint8_t dance_min_dance_step(tap_dance_state_t *state);
void dance_min_finished(tap_dance_state_t *state, void *user_data);
void dance_min_reset(tap_dance_state_t *state, void *user_data);

void on_dance_min(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_NUBS);
        tap_code16(KC_NUBS);
        tap_code16(KC_NUBS);
    }
    if(state->count > 3) {
        tap_code16(KC_NUBS);
    }
}

uint8_t dance_min_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_min_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_min_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_NUBS); break;
        case SINGLE_HOLD: register_code16(S(KC_NUBS)); break;
        case DOUBLE_TAP: register_code16(KC_NUBS); register_code16(KC_NUBS); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_NUBS); register_code16(KC_NUBS);
    }
}

void dance_min_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_NUBS); break;
        case SINGLE_HOLD: unregister_code16(S(KC_NUBS)); break;
        case DOUBLE_TAP: unregister_code16(KC_NUBS); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(S(KC_NUBS)); break;
    }
    dance_state.step = 0;
}


void on_dance_plus(tap_dance_state_t *state, void *user_data);
uint8_t dance_plus_dance_step(tap_dance_state_t *state);
void dance_plus_finished(tap_dance_state_t *state, void *user_data);
void dance_plus_reset(tap_dance_state_t *state, void *user_data);

void on_dance_plus(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_RBRC);
        tap_code16(KC_RBRC);
        tap_code16(KC_RBRC);
    }
    if(state->count > 3) {
        tap_code16(KC_RBRC);
    }
}

uint8_t dance_plus_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_plus_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_plus_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_RBRC); break;
        case SINGLE_HOLD: register_code16(S(KC_RBRC)); break;
        case DOUBLE_TAP: register_code16(KC_RBRC); register_code16(KC_RBRC); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_RBRC); register_code16(KC_RBRC);
    }
}

void dance_plus_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_RBRC); break;
        case SINGLE_HOLD: unregister_code16(S(KC_RBRC)); break;
        case DOUBLE_TAP: unregister_code16(KC_RBRC); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(S(KC_RBRC)); break;
    }
    dance_state.step = 0;
}

void on_dance_tab(tap_dance_state_t *state, void *user_data);
uint8_t dance_tab_dance_step(tap_dance_state_t *state);
void dance_tab_finished(tap_dance_state_t *state, void *user_data);
void dance_tab_reset(tap_dance_state_t *state, void *user_data);

void on_dance_tab(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_TAB);
        tap_code16(KC_TAB);
        tap_code16(KC_TAB);
    }
    if(state->count > 3) {
        tap_code16(KC_TAB);
    }
}

uint8_t dance_tab_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_tab_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_tab_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_TAB); break;
        case SINGLE_HOLD: register_code16(KC_F); break;
        case DOUBLE_TAP: register_code16(KC_TAB); register_code16(KC_TAB); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_TAB); register_code16(KC_TAB);
    }
}

void dance_tab_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_TAB); break;
        case SINGLE_HOLD: unregister_code16(KC_F); break;
        case DOUBLE_TAP: unregister_code16(KC_TAB); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_TAB); break;
    }
    dance_state.step = 0;
}
void on_dance_z(tap_dance_state_t *state, void *user_data);
uint8_t dance_z_dance_step(tap_dance_state_t *state);
void dance_z_finished(tap_dance_state_t *state, void *user_data);
void dance_z_reset(tap_dance_state_t *state, void *user_data);

void on_dance_z(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_Z);
        tap_code16(KC_Z);
        tap_code16(KC_Z);
    }
    if(state->count > 3) {
        tap_code16(KC_Z);
    }
}

uint8_t dance_z_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_z_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_z_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_Z); break;
        case SINGLE_HOLD: register_code16(KC_1); break;
        case DOUBLE_TAP: register_code16(KC_Z); register_code16(KC_Z); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_Z); register_code16(KC_Z);
    }
}

void dance_z_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_Z); break;
        case SINGLE_HOLD: unregister_code16(KC_1); break;
        case DOUBLE_TAP: unregister_code16(KC_Z); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_Z); break;
    }
    dance_state.step = 0;
}
void on_dance_x(tap_dance_state_t *state, void *user_data);
uint8_t dance_x_dance_step(tap_dance_state_t *state);
void dance_x_finished(tap_dance_state_t *state, void *user_data);
void dance_x_reset(tap_dance_state_t *state, void *user_data);

void on_dance_x(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_X);
        tap_code16(KC_X);
        tap_code16(KC_X);
    }
    if(state->count > 3) {
        tap_code16(KC_X);
    }
}

uint8_t dance_x_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_x_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_x_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_X); break;
        case SINGLE_HOLD: register_code16(KC_2); break;
        case DOUBLE_TAP: register_code16(KC_X); register_code16(KC_X); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_X); register_code16(KC_X);
    }
}

void dance_x_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_X); break;
        case SINGLE_HOLD: unregister_code16(KC_2); break;
        case DOUBLE_TAP: unregister_code16(KC_X); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_X); break;
    }
    dance_state.step = 0;
}
void on_dance_c(tap_dance_state_t *state, void *user_data);
uint8_t dance_c_dance_step(tap_dance_state_t *state);
void dance_c_finished(tap_dance_state_t *state, void *user_data);
void dance_c_reset(tap_dance_state_t *state, void *user_data);

void on_dance_c(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_C);
        tap_code16(KC_C);
        tap_code16(KC_C);
    }
    if(state->count > 3) {
        tap_code16(KC_C);
    }
}

uint8_t dance_c_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_c_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_c_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_C); break;
        case SINGLE_HOLD: register_code16(KC_3); break;
        case DOUBLE_TAP: register_code16(KC_C); register_code16(KC_C); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_C); register_code16(KC_C);
    }
}

void dance_c_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_C); break;
        case SINGLE_HOLD: unregister_code16(KC_3); break;
        case DOUBLE_TAP: unregister_code16(KC_C); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_C); break;
    }
    dance_state.step = 0;
}

void on_dance_v(tap_dance_state_t *state, void *user_data);
uint8_t dance_v_dance_step(tap_dance_state_t *state);
void dance_v_finished(tap_dance_state_t *state, void *user_data);
void dance_v_reset(tap_dance_state_t *state, void *user_data);

void on_dance_v(tap_dance_state_t *state, void *user_data) {
    if(state->count == 3) {
        tap_code16(KC_V);
        tap_code16(KC_V);
        tap_code16(KC_V);
    }
    if(state->count > 3) {
        tap_code16(KC_V);
    }
}

uint8_t dance_v_dance_step(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return SINGLE_TAP;
        else return SINGLE_HOLD;
    } else if (state->count == 2) {
        if (state->interrupted) return DOUBLE_SINGLE_TAP;
        else if (state->pressed) return DOUBLE_HOLD;
        else return DOUBLE_TAP;
    }
    return MORE_TAPS;
}
void dance_v_finished(tap_dance_state_t *state, void *user_data) {
    dance_state.step = dance_v_dance_step(state);
    switch (dance_state.step) {
        case SINGLE_TAP: register_code16(KC_V); break;
        case SINGLE_HOLD: register_code16(KC_5); break;
        case DOUBLE_TAP: register_code16(KC_V); register_code16(KC_V); break;
        case DOUBLE_SINGLE_TAP: tap_code16(KC_V); register_code16(KC_V);
    }
}

void dance_v_reset(tap_dance_state_t *state, void *user_data) {
    wait_ms(10);
    switch (dance_state.step) {
        case SINGLE_TAP: unregister_code16(KC_V); break;
        case SINGLE_HOLD: unregister_code16(KC_5); break;
        case DOUBLE_TAP: unregister_code16(KC_V); break;
        case DOUBLE_SINGLE_TAP: unregister_code16(KC_V); break;
    }
    dance_state.step = 0;
}

tap_dance_action_t tap_dance_actions[] = {
    [DANCE_PUNTO] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_punto, dance_punto_finished, dance_punto_reset),
    [DANCE_VIRGOLA] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_virgola, dance_virgola_finished, dance_virgola_reset),
    [DANCE_A] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_a, dance_a_finished, dance_a_reset),
    [DANCE_E] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_e, dance_e_finished, dance_e_reset),
    [DANCE_I] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_i, dance_i_finished, dance_i_reset),
    [DANCE_U] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_u, dance_u_finished, dance_u_reset),
    [DANCE_MIN] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_min, dance_min_finished, dance_min_reset),
    [DANCE_TAB] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_tab, dance_tab_finished, dance_tab_reset),
    [DANCE_V] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_v, dance_v_finished, dance_v_reset),
    [DANCE_C] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_c, dance_c_finished, dance_c_reset),
    [DANCE_X] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_x, dance_x_finished, dance_x_reset),
    [DANCE_Z] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_z, dance_z_finished, dance_z_reset),
    [DANCE_PLUS] = ACTION_TAP_DANCE_FN_ADVANCED(on_dance_plus, dance_plus_finished, dance_plus_reset)
};
